<?php

/**
 * @file
 * Module file for the utility_nav module.
 */

use Drupal\block\Entity\Block;

/**
 * @param $variables
 */
function utility_nav_preprocess_page(&$variables)
{
  // Add CSS
  $variables['#attached']['library'][] = 'utility_nav/utility-nav';
}

function utility_nav_theme($existing, $type, $theme, $path) {
  return [
   'menu__accounts__utility_menu_blocks' => [
      'template' => 'menu--accounts--utility-menu-blocks',
      'base hook' => 'menu'
    ],
   'menu__accounts__utility_mobile_accounts' => [
      'template' => 'menu--accounts--utility-mobile-accounts',
      'base hook' => 'menu'
    ],
   'accounts__utility_menu_blocks' => [
      'template' => 'accounts--utility-menu-blocks',
      'base hook' => 'block'
    ],
   'accounts__utility_mobile_accounts' => [
      'template' => 'accounts--utility-mobile-accounts',
      'base hook' => 'block'
    ],
   'info_for__utility_menu_blocks' => [
      'template' => 'info-for--utility-menu-blocks',
      'base hook' => 'block'
    ],
   'info_for__utility_mobile_info' => [
      'template' => 'info-for--utility-mobile-info',
      'base hook' => 'block'
    ],
    'menu__info_for__utility_mobile_info' => [
       'template' => 'menu--info-for--utility-mobile-info',
       'base hook' => 'menu'
     ],
  ];
}

function utility_nav_preprocess_block(&$variables) {
  $util_menus = array(
    'system_menu_block:accounts',
    'system_menu_block:info-for',
  );
  if (in_array($variables['plugin_id'], $util_menus)) {
    $region = Block::load($variables['elements']['#id'])->getRegion();
    $variables['content']['#attributes']['region'] = $region;
  }
}

function utility_nav_theme_suggestions_block_alter(array &$suggestions, array $variables) {
  $util_blocks = array(
    'fixed_block_content:system_status_fixed_block',
    'fixed_block_content:ask_a_librarian',
    'system_menu_block:accounts',
    'system_menu_block:info-for',
  );
  if (in_array($variables['elements']['#plugin_id'], $util_blocks)) {
    if (isset($variables['elements']['#id'])) {
      $plugin_id = $variables['elements']['#plugin_id'];
      $block_name = substr($plugin_id, strpos($plugin_id, ':') + 1);
      $region = Block::load($variables['elements']['#id'])->getRegion();
      $suggestion = $block_name . '__' . $region;
      $suggestions[] = str_replace('-', '_', $suggestion);
    }
  }
}

function utility_nav_theme_suggestions_menu_alter(&$suggestions, array $variables) {
  if (isset($variables['attributes']['region'])) {
    $suggestion = 'menu__' . $variables['menu_name'] . '__' . $variables['attributes']['region'];
    $suggestions[] = str_replace('-', '_', $suggestion);
  }
}
