<?php

/**
 * @file
 * Module file for newsroom module.
 */

use Drupal\views\ViewExecutable;

/**
* Implements hook_views_pre_render().
*/
function newsroom_views_pre_render(ViewExecutable $view) {
  if (empty($view) || empty($view->storage->id())) {
    return;
  }
  if ($view->storage->id() == 'news' || $view->storage->id() == 'news_navigation') {
    $view->element['#attached']['library'][] = 'newsroom/news_page';
  }
  if ($view->storage->id() == 'news_events_block') {
    // reordered results with the first article with an image
    // promoted to the top of the list
    $results = array();
    // boolean tracker of whether we have found an image
    $found_image = 0;
    foreach ($view->result as $row) {
      if ($found_image && count($results) >= 6) {
        // halt the loop once we have found an article with an image,
        // and no more than 5 other articles
        break;
      }
      $entity = $row->_entity;
    	$image = $entity->get('field_umdt_ct_article_image')->getValue();
    	if (!$found_image && count($image) > 0) {
        // this is the first article we've found with an image;
        // put it at the head of the results list
        array_unshift($results, $row);
        $found_image = 1;
      } else {
        if (count($results) - $found_image < 5) {
          // add up to 5 other rows to the end of the results array
          array_push($results, $row);
        }
      }
    }
    // iterate over the rows and set index values.
    // See: https://drupal.stackexchange.com/a/303973
    foreach ($results as $key => $row) {
      $row->index = $key;
    }
    $view->result = $results;

    $view->element['#attached']['library'][] = 'newsroom/newsroom';
  }
}

/**
 * Implements hook_preprocess_views_view_unformatted.
 */
function newsroom_preprocess_views_view_unformatted(&$variables) {
  $view = $variables["view"];
  $viewId = $view->id();

  if ($viewId == 'news_events_block') {
    if (!empty($variables['rows'][0])) {
      $variables['rows'][0]['attributes']->addClass('news-featured');
    }
  }
}
