<?php

/**
 * @file
 * Module file for lib_cal module.
 */

/**
 * Implements hook_theme().
 */
function lib_cal_theme() {
  return [
    'lib_cal_block' => [
      'variables' => [
        'events' => '',
        'no_events' => '',
      ],
    ],
    'lib_hours_today' => [
      'variables' => [
        'hours' => '',
        'row_class' => '',
        'grid_class' => '',
        'current_date' => '',
        'shady_grove_url' => '',
        'hours_class' => '',
        'locations' => '',
        'urls' => '',
      ],
    ],
    'lib_hours_today_util' => [
      'variables' => [
        'hours' => '',
        'row_class' => '',
        'grid_class' => '',
        'current_date' => '',
        'shady_grove_url' => '',
        'all_libraries_url' => '',
        'is_mobile' => '',
        'hours_class' => '',
        'locations' => '',
        'urls' => '',
      ],
    ],
    'lib_hours_range' => [
      'variables' => [
        'hours' => '',
        'row_class' => '',
        'grid_class' => '',
        'current_date' => '',
        'week_date' => '',
        'shady_grove_url' => '',
        'hours_class' => '',
        'locations' => '',
        'urls' => '',
      ],
    ],
    'lib_button' => [
      'variables' => [
        'button_text' => '',
        'button_url' => '',
      ],
    ],
  ];
}
