<?php

/**
 * @file
 * Module file for lib_cal module.
 */

/**
 * Implements hook_theme().
 */
function lib_cal_theme() {
  return [
    'lib_cal_block' => [
      'variables' => [
        'events' => '',
      ],
    ],
    'lib_hours_today' => [
      'variables' => [
        'hours' => '',
        'branch_prefix' => '',
        'branch_suffix' => '',
        'row_class' => '',
        'grid_class' => '',
        'current_date' => '',
      ],
    ],
    'lib_hours_today_util' => [
      'variables' => [
        'hours' => '',
        'branch_prefix' => '',
        'branch_suffix' => '',
        'row_class' => '',
        'grid_class' => '',
        'current_date' => '',
        'shady_grove_url' => '',
        'all_libraries_url' => '',
        'is_mobile' => '',
      ],
    ],
    'lib_hours_range' => [
      'variables' => [
        'hours' => '',
        'branch_prefix' => '',
        'branch_suffix' => '',
        'row_class' => '',
        'grid_class' => '',
        'current_date' => '',
      ],
    ],
  ];
}
