<?php

/**
 * @file
 * Module file for the hero_search module.
 */

/**
 * Implements hook_theme().
 */
function hero_search_theme() {
  return [
    'hero_search_block' => [
      'variables' => [
        'hero_search_title' => '',
        'hero_search_form' => '',
        'hero_search_alert' => '',
        'hero_search_more_links' => '',
        'hero_discover_links' => '',
        'hero_top_content' => '',
        'hero_bottom_content' => '',
      ],
    ],
    'hero_search_form' => [
      'render element' => 'form',
    ],
  ];
}
