<?php
/**
 * @file
 * Module file for the system_status module
 */

/**
 * @param $variables
 */
function system_status_preprocess_page(&$variables)
{
  $system_status_url = Drupal\Core\Url::fromRoute('system_status.status_json')->toString();
  // pass variable to Drupal.Settings
  $variables['#attached']['drupalSettings']['system_status']['system_status_url'] = $system_status_url;
}

/**
 * Implements hook_theme().
 */
function system_status_theme() {
  return [
    'system_status_fixed_block__utility_menu_blocks' => [
       'template' => 'system-status-fixed-block--utility-menu-blocks',
       'base hook' => 'block'
    ],
    'system_status_fixed_block__utility_mobile_systems' => [
       'template' => 'system-status-fixed-block--utility-mobile-systems',
       'base hook' => 'block'
    ],
  ];
}
