<?php

/**
 * @file
 * Module file for the ask_us module.
 */

/**
 * Implements hook_theme().
 */
function ask_us_theme() {
  return [
    'ask_a_librarian_util' => [
      'variables' => [
        'libchat_id' => '',
        'ask_title' => '',
        'faq_form' => '',
        'link_1_url' => '',
        'link_1_text' => '',
        'link_2_url' => '',
        'link_2_text' => '',
        'social_button_1' => '',
        'social_button_2' => '',
      ],
    ],
    'ask_a_librarian_util_mobile' => [
      'variables' => [
        'libchat_id' => '',
        'ask_title' => '',
        'faq_form' => '',
        'link_1_url' => '',
        'link_1_text' => '',
        'link_2_url' => '',
        'link_2_text' => '',
        'social_button_1' => '',
        'social_button_2' => '',
      ],
    ],
  ];
}

