<?php

/**
 * @file
 * Module file for the ask_us module.
 */

/**
 * Implements hook_theme().
 */
function ask_us_theme() {
  return [
    'ask_a_librarian__utility_menu_blocks' => [
       'template' => 'ask-a-librarian--utility-menu-blocks',
       'base hook' => 'block'
    ],
    'ask_a_librarian__utility_mobile_help' => [
       'template' => 'ask-a-librarian--utility-mobile-help',
       'base hook' => 'block'
    ],
  ];
}

