<?php

/**
 * @file
 * newsroom module install file.
 */

/**
 * Install newsroom configuration.
 */
function newsroom_update_8001() {
  \Drupal::service('config.installer')->installDefaultConfig('module', 'newsroom');
}

/**
 * News navigation view added.
 */
function newsroom_update_8002() {
  \Drupal::service('config.installer')->installDefaultConfig('module', 'newsroom');
}

/**
 * Implements hook_uninstall
 */
function newsroom_uninstall() {
}
