<?php

/**
 * @file
 * Helpers and hook overrides for umd_commands.
 */


// Implements hook_simple_sitemap_arbitrary_links_alter()
function umd_commands_simple_sitemap_arbitrary_links_alter(&$arbitrary_links, $sitemap){
  if ($sitemap->id() === 'worldsfairs') {
    # $arbitrary_links[] = [
    #   'url' => 'https://some-arbitrary-link/',
    #   'priority' => '0.5',

    #   // An ISO8601 formatted date.
    #   'lastmod' => '2012-10-12T17:40:30+02:00',

    #   'changefreq' => 'weekly',
    #   'images' => [
    #     ['path' => 'https://path-to-image.png'],
    #   ],

      // Add alternate URLs for every language of a multilingual site.
      // Not necessary for monolingual sites.
      # 'alternate_urls' => [
      #    'en' => 'https://this-is-your-life.net/de/tyler',
      #    'de' => 'https://this-is-your-life.net/en/tyler',
      # ],
    # ];
  }
}
