<?php

use Drupal\mirador_viewer\Controller\DisplayMiradorController;

/**
 * Implements hook_theme().
 */
function mirador_viewer_theme() {
  return [
    'mirador_viewer' => [
      'variables' => [
        'iiif_server' => '',
        'iiif_viewer' => '',
        'object_id' => '',
        'collection_id' => '',
        'error_message' => '',
        'attributes' => [],
      ],
    ],
    'static_viewer' => [
      'variables' => [
        'body' => '',
        'attachments' => '',
        'images' => '',
      ],
    ],
  ];
}

