<?php

use Drupal\Core\Url;
use Drupal\views\Plugin\views\display;
use Drupal\Core\Entity\EntityInterface;
use Drupal\block\Entity\Block;
use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\Component\Utility\Html;

/**
 * @file
 * Module file for bento module.
 */

use Drupal\views\ViewExecutable;
use Drupal\views\ResultRow;

/**
 * Implements hook_theme().
 */
function bento_theme() {
  return [
    'bento_empty_sidebar' => [
      'variables' => [
        'bento_empty_message' => '',
      ],
    ],
    'bento_search_block' => [
      'variables' => [
        'bento_search_form' => '',
      ],
    ],
    'bento_summary_block' => [
      'variables' => [
        'search_targets' => '',
      ],
    ],
    'bento_search_categories_block' => [
      'variables' => [
        'search_categories' => '',
        'search_categories_heading' => '',
      ],
    ],
    'bento_resource_types_block' => [
      'variables' => [
        'resource_types' => '',
        'resource_types_heading' => '',
      ],
    ],
    'bento_other_resources_block' => [
      'variables' => [
        'other_resources' => '',
        'other_resources_heading' => '',
      ],
    ],
    'bento_looking_more_block' => [
      'variables' => [
        'looking_more_text' => '',
        'looking_more_url' => '',
        'looking_more_heading' => '',
      ],
    ],
    'bento_more_block' => [
      'variables' => [
        'search_options' => '',
        'query' => '',
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_views_view_field().
 */
function bento_preprocess_views_view_field(&$variables) {
  $view = $variables['view'];
  if (!empty($view->id()) && str_contains($view->id(), 'bento_')) {
    if (!empty($variables['field']->options['admin_label']) && $variables['field']->options['admin_label'] == 'Format') {
      $field_id = $variables['field']->options['id'];
      $raw_output = $variables['field']->getValue($variables['row']);
      $variables['output'] = [
        '#markup' => '<span class="' . bento_icon_map($raw_output). '"></span> <span class="bento-value">' . bento_format_map($raw_output) . '</span>',
      ];
    }
  }
}

/**
* Implements hook_views_pre_render().
*/
function bento_views_pre_render(ViewExecutable $view) {
  if (empty($view) || empty($view->id())) {
    return;
  }
  if (str_contains($view->id(), 'bento_')) {
    if (!empty($view->raw_data)) {
      $raw_data = $view->raw_data;
      $result_count = !empty($raw_data['total']) ? $raw_data['total'] : null;
      if (!empty($result_count)) {
        if ($result_count > 100 && $view->id() == 'bento_website_search') {
          $result_count = 100;
        }
        $view->pager->total_items = $result_count;
        $view->total_rows = $result_count;
        $view->pager->updatePageInfo();
      }
    }
  }
}

function bento_views_post_execute(ViewExecutable $view) {
  if (str_contains($view->storage->id(), 'bento_') && $view->id() != 'bento_website_search' && $view->id() != 'bento_best_bets') {
    $display = $view->getDisplay();
    $result_id = null;
    $footer_content = null;
    if (!empty($display->display['display_options']['css_class'])) {
      $result_id = str_replace('_', '-',  $display->display['display_options']['css_class']) . '-total';
    }

    $title_raw = $view->getTitle();
    $title_array = explode('|', $title_raw);
    $title = !empty($title_array[1]) ? $title_array[0] : $title_raw;
    $subtitle = !empty($title_array[1]) ? $title_array[1] : $title_raw . ' results from UMD Libraries';
    $fa_icons = !empty($title_array[2]) ? 'fas fa-solid ' . $title_array[2] : 'fas fa-regular fa-link';

    $footer_title = $title;
    if (!empty($subtitle) && str_contains($subtitle, 'UMD Discover')) {
      $footer_title = 'UMD Discover';
    }
    $header_content = '
      <header>
        <h2>' . $title . '</h2>
        <p>' . $subtitle . '</p>
      </header>';
    if (!empty($view->raw_data['total']) && !empty($view->raw_data['module_link']) && count($view->raw_data['results']) > 0) {
      $real_total = $view->raw_data['total'];
      $query_string = $view->raw_data['module_link'];
      if ($real_total > 0) {
        $footer_content = '
          <div class="bento-attachment" id="' . $result_id . '" data-total="' . $real_total . '">
            <a id="bento-search-footer-' . Html::getId($title) . '" href="' . str_replace('"', '%22', $query_string) . '" title="See all ' . number_format($real_total, 0, ".", ",") . ' ' . $title . ' results">See all ' . number_format($real_total, 0, ".", ",") . ' results from ' . $footer_title . '</a>
          </div>';
        $header_content = '
          <header>
            <h2><a href="'. str_replace('"', '%22', $query_string) . '" id="bento-search-header-' . Html::getId($title) . '">' . $title . '</a></h2>
            <p>' . $subtitle . '</p>
          </header>';
      } else {
        $footer_content = '
          <div id="' . $result_id . '" data-total="0"></div>';
      } 
    } elseif (!empty($result_id)) {
      $footer_content = '
        <div id="' . $result_id . '" data-total="0"></div>';
    }
    $view->attachment_after = array('#markup' => $footer_content);
    $view->attachment_before = array('#markup' => $header_content);
  }
}

function bento_views_pre_view(ViewExecutable $view, $display_id, array &$args) {
  if (!empty($view) && !empty($view->id()) && (str_contains($view->id(), 'bento_'))) {
    $bento_search = \Drupal::request()->query->get('query');
    if (!empty($bento_search)) {
      $args[0] = $bento_search;
    }
    if ($view->id() == 'bento_website_search') {
      $page = \Drupal::request()->query->get('page');
      if (!empty($page)) {
        $page_raw = (int)$page;
        if ($page_raw > 0) {
          $args[1] = $page_raw;
        } else {
          $args[1] = "0";
        }
      } else {
        $args[1] = "0";
      }
    }
  }
}

function bento_icon_map($raw_name) {
  $icon_map = [
    "archival_material" => "result-icons fas fa-archive",
    "article" => "result-icons fas fa-file-alt",
    "audio" => "result-icons fas fa-headphones",
    "audio_book" => "result-icons fas fa-file-audio",
    "book" => "result-icons fas fa-book",
    "cd" => "result-icons fas fa-compact-disc",
    "computer_file" => "result-icons far fa-file",
    "dvd" => "result-icons fas fa-compact-disc",
    "e_book" => "result-icons fas fa-tablet-alt",
    "e_music" => "result-icons fas fa-headphones",
    "e_video" => "result-icons fas fa-video",
    "image" => "result-icons fas fa-image",
    "journal" => "result-icons fas fa-book-open",
    "journals" => "result-icons fas fa-book-open",
    "lp" => "result-icons fas fa-compact-disc",
    "map" => "result-icons fas fa-map-marked",
    "newspaper" => "result-icons far fa-newspaper",
    "score" => "result-icons fas fa-music",
    "thesis" => "result-icons fas fa-graduation-cap",
    "video_recording" => "result-icons fas fa-video",
    "other" => "result-icons fas fa-question",
    "database" => "result-icons fas fa-database margin-top-10",
    "web_page" => "result-icons fas fa-link",
    "book_chapter" => "result-icons fas fa-bookmark",
    "conference_proceeding" => "result-icons fas fa-clipboard",
    "dissertation" => "result-icons fas fa-book",
    "kit" => "result-icons fas fa-box",
    "manuscript" => "result-icons fas fa-file-lines",
    "text_resource" => "result-icons fas fa-file-lines",
    "video" => "result-icons fas fa-video",
    "web_resource" => "result-icons fas fa-window-maximize",
  ];
  return !empty($icon_map[$raw_name]) ? $icon_map[$raw_name] : $icon_map['other'];
}

function bento_format_map($raw_name) {
  $format_map = [
    "archival_material" => "Archival Material",
    "article" => "Article",
    "audio" => "Audio",
    "audio_book" => "Audio Book",
    "book" => "Book",
    "cd" => "CD",
    "computer_file" => "Computer File",
    "dvd" => "DVD",
    "e_book" => "eBook",
    "e_music" => "eMusic",
    "e_video" => "eVideo",
    "image" => "Image",
    "journal" => "Journal",
    "journals" => "Journals",
    "lp" => "LP",
    "map" => "Map",
    "newspaper" => "Newspaper",
    "score" => "Score",
    "thesis" => "Thesis",
    "video_recording" => "Video Recording",
    "other" => "Other",
    "database" => "Database",
    "web_page" => "Webpage",
    "book_chapter" => "Book Chapter",
    "conference_proceeding" => "Conference Proceeding",
    "dissertation" => "Dissertation",
    "kit" => "Kit",
    "manuscript" => "Manuscript",
    "text_resource" => "Text Resource",
    "video" => "Video",
    "web_resource" => "Web Resource",
  ];
  return !empty($format_map[$raw_name]) ? $format_map[$raw_name] : "Other";
}
