name: Libraries' Configuration
description: Adds Libraries' Configuration menu item to the configuration page.

package: 'UMD Services'
configure: libraries_configuration.admin_settings_form
dependencies:
  - easy_install
type: module

core_version_requirement: ^11 || ^9 || ^10
