<?php

/**
 * @file
 * Ut_block module install file.
 */

/**
 * Reset all paragraph fields to match standard config.
 */
function ut_block_update_8001() {
  \Drupal::service('config.installer')->installDefaultConfig('module', 'ut_block');
}

function ut_block_update_8002() {
  \Drupal::service('config.installer')->installDefaultConfig('module', 'ut_block');
}

function ut_block_update_8003() {
  \Drupal::service('config.installer')->installDefaultConfig('module', 'ut_block');
}
