<?php

/**
 * @file
 * Module file for equipment_tracking module.
 */

/**
 * Implements hook_theme().
 */
function equipment_tracking_theme() {
  return [
    'aleph_equipment_available' => [
      'variables' => [
        'equipment_count' => '',
        'equipment_sysnum' => '',
        'equipment_mindue' => '',
      ],
    ],
  ];
}


/**
 * Implements hook_form_views_exposed_form_alter().
 *
 * This should maintain facets across searches.
 *
 * @see
 *   https://www.drupal.org/project/facets/issues/2767389
 */
function equipment_tracking_form_views_exposed_form_alter(&$form, $form_state, $form_id) {
  $params = \Drupal::requestStack()->getCurrentRequest()->query->all();
  $facet_manager = \Drupal::service('facets.manager');
  $facets = $facet_manager->getEnabledFacets();
  foreach ($facets as $facet) {
    $filter_keys[] = empty($facet->getFacetSourceConfig()->getFilterKey()) ? 'f' : $facet->getFacetSourceConfig()->getFilterKey();

  }
  if (!empty($filter_keys)) {
    foreach (array_unique($filter_keys) as $filter_key) {
     if (!empty($params[$filter_key]) && !empty($param_values = $params[$filter_key])) {
        // Add facet parameters to hidden fields in the forms.
        foreach ($param_values as $key => $value) {
          $form[$filter_key . '[' . $key . ']'] = [
            '#type' => 'hidden',
            '#value' => $value,
          ];
        }
      }
    }
  }
}

