<?php

/**
 * @file
 * Module file for top_textbooks module.
 */

use Drupal\views\ViewExecutable;

/**
 * Implements hook_theme().
 */
function top_textbooks_theme() {
  return [
    'textbook_availability_field' => [
      'variables' => [
        'textbook_count' => '',
        'textbook_mindue' => '',
        'textbook_sysnum' => '',
        'error' => '',
      ],
    ],
  ];
}

/**
* Implements hook_views_pre_render().
*/
function top_textbooks_views_pre_render(ViewExecutable $view) {
  if (empty($view) || empty($view->storage->id())) {
    return;
  }
  if ($view->storage->id() == 'top_textbooks') {
    $view->element['#attached']['library'][] = 'top_textbooks/search-page';
  }
}
